### ISSUE TITLE
User timeline performance

### ISSUE THREAD

**Issue by fridge7809** [DevOps-2024-group-p/maxitwit#128]
User timeline performance is currently 2x slower than public timeline. Can we look at our schema/queries and see what we can improve?

**Comment by RobertSluka** [comment]
![Screenshot from 2024-04-26 14-11-36](https://github.com/DevOps-2024-group-p/maxitwit/assets/107124774/7fe0b8b8-ae11-4e45-9f0c-50eb2ca1da2f)
After analyzing our indexes, I came to conclusion that they are implemented/used correctly and therefore we would have to do further investigation to figure this issue. Probably setting up the async or pagination to speed it up :)
