### ISSUE TITLE
 Add Maintainability and Technical Debt estimation tools to your projects

### ISSUE THREAD

**Issue by fridge7809** [DevOps-2024-group-p/maxitwit#133]
[Guide](https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_07/README_TASKS.md#2-add-maintainability-and-technical-debt-estimation-tools-to-your-projects)

**Comment by RobertSluka** [comment]
![image](https://github.com/DevOps-2024-group-p/maxitwit/assets/107124774/dd2f1ebd-5fd6-4839-9e0d-d6b097a94848)
if anyone hasn't used his trial period yet , would be awesome if we did once again just to see the differences among them :)

**Comment by fridge7809** [comment]
Sonarcloud added to the org and began implementing suggestions in #150
